name: "units-test"
on:
  pull_request:
  push:
    branches:
      - main
      - "releases/*"

jobs:
  # unit tests
  units:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm ci
      - run: npm test

  # test action works running from the graph
  test:
    runs-on: ubuntu-latest
    needs: units
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/action.yml
        id: issue
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: Test Issue
          body: Test issue body
          assignees: |
            ikramtouir
      - run: echo ${{ steps.issue.outputs.issue }}